module.exports = {
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    CALLBACK_URL: process.env.CALLBACK_URL,
    MONGODB_SHORT_SRV_CONNECTION_STRING: process.env.MONGODB_SHORT_SRV_CONNECTION_STRING,
    COOKIE_KEY: process.env.COOKIE_KEY
}